### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by MarkSwanson** [diwic/fdringbuf-rs#1]
I'm running on at 32-bit Linux Ubuntu 14 box.
I updated rustc today:
$ rustc --version
rustc 1.0.0-nightly (2fc8b1e7c 2015-03-07) (built 2015-03-08)

$ cargo bench
    Updating registry `https://github.com/rust-lang/crates.io-index`
 Downloading nix v0.2.3
 Downloading bitflags v0.1.1
   Compiling bitflags v0.1.1
   Compiling fdringbuf v0.0.1 (file:///home/me/src/external/fdringbuf-rs)
src/fdbuf.rs:31:84: 31:119 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
src/fdbuf.rs:31     let e = unsafe { ::libc::write(fd, &1u64 as *const _ as *const ::libc::c_void, ::std::mem::size_of::<u64>() as u64) };
                                                                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/fdbuf.rs:41:74: 41:109 error: mismatched types:
 expected `u32`,
    found `u64`
(expected u32,
    found u64) [E0308]
src/fdbuf.rs:41     let e = unsafe { ::libc::read(fd, b.as_ptr() as *mut ::libc::c_void, ::std::mem::size_of::<Arr>() as u64) };
                                                                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to 2 previous errors
Build failed, waiting for other jobs to finish...
Could not compile `fdringbuf`.

**Comment by diwic** [comment]
Thanks for noticing! Should be fixed now.
